#!/usr/bin/env python3
#
# Code based on i2rs-wg by Edwin Cordeiro. See https://github.com/i2rs-wg for he original script.
#
# Extensively modified by Daniel R. Franklin for UTS 49202 Communication Protocols labs.
#
# Report bugs to Daniel.Franklin@uts.edu.au
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# On Debian systems, the full text of the GNU General Public License version
# 2 can be found in the file
#
# /usr/share/common-licenses/GPL-2'.

from mininet.topo import Topo
from mininet.net import Mininet
from mininet.log import lg, info, setLogLevel
from mininet.util import dumpNodeConnections, quietRun, moveIntf
from mininet.cli import CLI
from mininet.node import Switch, OVSKernelSwitch
from mininet.nodelib import NAT, LinuxBridge
from mininet.link import TCLink
from mininet.link import Intf

from subprocess import Popen, PIPE, check_output
from time import sleep, time
from multiprocessing import Process
import argparse
import atexit
import math

import sys
import signal
import os
from termcolor import cprint
import time
import re
import subprocess

from lib import config
from lib import mininet_utils

server_processes = []

setLogLevel ('info')

parser = argparse.ArgumentParser ("Create a simple model of an NBN service")

def ranged_type (value_type, min_value, max_value):
	def range_checker(arg: str):
		try:
			f = value_type(arg)
		except ValueError:
			raise argparse.ArgumentTypeError (f'must be a valid {value_type}')
	
		if f < min_value or f > max_value:
			raise argparse.ArgumentTypeError (f'must be within range [{min_value}, {max_value}]')
		
		return f

# Return function handle to checking function
	return range_checker

parser.add_argument ('--sleep', default = 3, type = int)
parser.add_argument ('-d', '--downstream', default = 400, type = ranged_type (float, 0, math.inf), help = 'Aggregation downstream bandwidth (Mb/s)')
parser.add_argument ('-u', '--upstream', default = 200, type = ranged_type (float, 0, math.inf), help = 'Aggregation upstream bandwidth (Mb/s)')
parser.add_argument ('--households', default = 32, type = ranged_type (int, 1, math.inf), help = 'Number of households to model')
parser.add_argument ('--clients-per-household', default = 2, type = ranged_type (int, 1, math.inf), help = 'Number of clients per household')
parser.add_argument ('-s', '--servers', default = 16, type = ranged_type (int, 1, math.inf), help = 'Number of CDN servers')
parser.add_argument ('-c', '--clients', default = None, type = ranged_type (int, 1, math.inf), help = 'Total number of clients; defaults to households * clients-per-household')
args = parser.parse_args ()

if args.clients is None:
	args.clients = args.households * args.clients_per_household

HOUSEHOLD_DOWNSTREAM = 150
HOUSEHOLD_UPSTREAM = 40
FIRST_CLIENT_SUBNET = 101
IPERF_BASE_PORT = 5201
IPERF_PORTS_PER_SERVER = 8
BIND_DIR = os.path.join (os.path.dirname (__file__), 'bind')
MGMT_DNS_IP = '10.10.10.254'

def build_mgmt_plan (households, clients_per_household, server_count):
	total_clients = households * clients_per_household
	plan = {
		'dns': 254,
		'r2': 2,
		'r3': 3,
		's2': 12,
		's3': 13,
		's4': 14,
		'servers': {},
		'household_switches': {},
		'household_routers': {},
		'clients': {},
	}

	next_octet = 20
	for key, count in [
		('servers', server_count),
		('household_switches', households),
		('household_routers', households),
		('clients', total_clients),
	]:
		last_octet = next_octet + count - 1
		if last_octet >= plan['dns']:
			raise ValueError ('Management subnet exhausted; reduce nodes or expand addressing plan')

		for index in range (1, count + 1):
			plan[key][index] = next_octet + index - 1

		next_octet = last_octet + 10

	return plan

try:
	MGMT_PLAN = build_mgmt_plan (args.households, args.clients_per_household, args.servers)
except ValueError as exc:
	parser.error (str (exc))

def zone_header ():
	serial = time.strftime ('%Y%m%d01')
	return (
		';\n'
		'; Auto-generated by nbn_testbed.py\n'
		';\n'
		'$TTL\t604800\n'
		'@\tIN\tSOA\tlocalhost. root.localhost. (\n'
		f'\t\t     {serial}\t\t; Serial\n'
		'\t\t\t 604800\t\t; Refresh\n'
		'\t\t\t  86400\t\t; Retry\n'
		'\t\t\t2419200\t\t; Expire\n'
		'\t\t\t 604800 )\t; Negative Cache TTL\n'
		';\n'
		'@\tIN\tNS\tlocalhost.\n\n'
	)

def write_zone_file (path, content):
	with open (path, 'w', encoding = 'utf-8') as handle:
		handle.write (content)

def generate_bind_files (bind_dir, households, clients_per_household, server_count, mgmt_plan):
	os.makedirs (bind_dir, exist_ok = True)

	named_conf_lines = [
		'//',
		'// Auto-generated by nbn_testbed.py',
		'//',
		'',
		'zone "mgmt.net" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.mgmt.net";',
		'};',
		'',
		'zone "home.net" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.home.net";',
		'};',
		'',
		'zone "nbn.net" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.nbn.net";',
		'};',
		'',
		'zone "rsp.net" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.rsp.net";',
		'};',
		'',
		'zone "cdn.net" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.cdn.net";',
		'};',
		'',
		'zone "10.10.10.in-addr.arpa" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.10.10.10";',
		'};',
		'',
		'zone "1.16.172.in-addr.arpa" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.172.16.1";',
		'};',
		'',
		'zone "1.20.172.in-addr.arpa" {',
		'\ttype master;',
		'\tfile "/etc/bind/db.172.20.1";',
		'};',
		'',
	]

	mgmt_records = [
		'; Management network (including DNS for our convenience)',
		'$ORIGIN mgmt.net.',
		'',
		f'rsp-gw-mgmt\tA\t10.10.10.{mgmt_plan["r2"]}',
		'r2-mgmt\t\tCNAME\trsp-gw-mgmt',
		f'cdn-gw-mgmt\tA\t10.10.10.{mgmt_plan["r3"]}',
		'r3-mgmt\t\tCNAME\tcdn-gw-mgmt',
		f's2-mgmt\t\tA\t10.10.10.{mgmt_plan["s2"]}',
		f's3-mgmt\t\tA\t10.10.10.{mgmt_plan["s3"]}',
		f's4-mgmt\t\tA\t10.10.10.{mgmt_plan["s4"]}',
		'',
	]

	reverse_mgmt_records = [
		'$ORIGIN 10.10.10.in-addr.arpa.',
		'',
		f'{mgmt_plan["r2"]}\tPTR\tr2-mgmt.mgmt.net.',
		f'{mgmt_plan["r3"]}\tPTR\tr3-mgmt.mgmt.net.',
		f'{mgmt_plan["s2"]}\tPTR\ts2-mgmt.mgmt.net.',
		f'{mgmt_plan["s3"]}\tPTR\ts3-mgmt.mgmt.net.',
		f'{mgmt_plan["s4"]}\tPTR\ts4-mgmt.mgmt.net.',
		'',
	]

	home_records = [
		'; Household client networks',
		'$ORIGIN home.net.',
		'',
	]

	nbn_records = [
		'$ORIGIN nbn.net.',
		'',
	]

	for household in range (1, households + 1):
		subnet_octet = FIRST_CLIENT_SUBNET + household - 1
		house_switch_octet = mgmt_plan['household_switches'][household]
		house_router_octet = mgmt_plan['household_routers'][household]

		mgmt_records.append (f's1h{household}-mgmt\tA\t10.10.10.{house_switch_octet}')
		mgmt_records.append (f'hr{household}-mgmt\tA\t10.10.10.{house_router_octet}')
		reverse_mgmt_records.append (f'{house_switch_octet}\tPTR\ts1h{household}-mgmt.mgmt.net.')
		reverse_mgmt_records.append (f'{house_router_octet}\tPTR\thr{household}-mgmt.mgmt.net.')

		home_records.append (f'house{household}-gw\tA\t192.168.{subnet_octet}.254')
		nbn_records.append (f'house{household}-cust\tA\t10.1.{household}.1')
		nbn_records.append (f'house{household}-rsp\tA\t10.1.{household}.2')

		home_reverse_records = [
			zone_header (),
			f'$ORIGIN {subnet_octet}.168.192.in-addr.arpa.\n\n',
		]
		nbn_reverse_records = [
			zone_header (),
			f'$ORIGIN {household}.1.10.in-addr.arpa.\n\n',
			f'1\tPTR\thouse{household}-cust.nbn.net.\n',
			f'2\tPTR\thouse{household}-rsp.nbn.net.\n',
		]

		for household_client in range (1, clients_per_household + 1):
			client_index = ((household - 1) * clients_per_household) + household_client
			client_mgmt_octet = mgmt_plan['clients'][client_index]
			client_ip = f'192.168.{subnet_octet}.{household_client}'

			mgmt_records.append (f'client{client_index}-mgmt\tA\t10.10.10.{client_mgmt_octet}')
			reverse_mgmt_records.append (f'{client_mgmt_octet}\tPTR\tclient{client_index}-mgmt.mgmt.net.')
			home_records.append (f'client{client_index}\tA\t{client_ip}')
			home_reverse_records.append (f'{household_client}\tPTR\tclient{client_index}.home.net.\n')

		home_reverse_records.append (f'254\tPTR\thouse{household}-gw.home.net.\n')

		write_zone_file (
			os.path.join (bind_dir, f'db.192.168.{subnet_octet}'),
			''.join (home_reverse_records)
		)
		write_zone_file (
			os.path.join (bind_dir, f'db.10.1.{household}'),
			''.join (nbn_reverse_records)
		)

		named_conf_lines.extend ([
			f'zone "{subnet_octet}.168.192.in-addr.arpa" {{',
			'\ttype master;',
			f'\tfile "/etc/bind/db.192.168.{subnet_octet}";',
			'};',
			'',
			f'zone "{household}.1.10.in-addr.arpa" {{',
			'\ttype master;',
			f'\tfile "/etc/bind/db.10.1.{household}";',
			'};',
			'',
		])

	mgmt_records.extend ([
		'',
		f'dns-mgmt\tA\t{MGMT_DNS_IP}',
		'dns\t\tCNAME\tdns-mgmt',
	])
	reverse_mgmt_records.extend ([
		'',
		'254\tPTR\tdns-mgmt.mgmt.net.',
	])

	cdn_records = [
		'$ORIGIN cdn.net.',
		'',
	]
	reverse_cdn_records = [
		'$ORIGIN 1.20.172.in-addr.arpa.',
		'',
	]
	for server_index in range (1, server_count + 1):
		server_ip = f'172.20.1.{server_index}'
		server_mgmt_octet = mgmt_plan['servers'][server_index]
		cdn_records.append (f'server{server_index}\tA\t{server_ip}')
		mgmt_records_entry = f'server{server_index}-mgmt\tA\t10.10.10.{server_mgmt_octet}'
		reverse_mgmt_entry = f'{server_mgmt_octet}\tPTR\tserver{server_index}-mgmt.mgmt.net.'
		reverse_cdn_records.append (f'{server_index}\tPTR\tserver{server_index}.cdn.net.')
		if mgmt_records_entry not in mgmt_records:
			mgmt_records.insert (-2, mgmt_records_entry)
		if reverse_mgmt_entry not in reverse_mgmt_records:
			reverse_mgmt_records.insert (-2, reverse_mgmt_entry)

	cdn_records.extend ([
		'gw\t\tA\t172.20.1.254',
		'r3\t\tCNAME\tgw',
	])
	reverse_cdn_records.append ('254\tPTR\tgw.cdn.net.')

	write_zone_file (
		os.path.join (bind_dir, 'named.conf.local'),
		'\n'.join (named_conf_lines) + '\n'
	)
	write_zone_file (
		os.path.join (bind_dir, 'db.mgmt.net'),
		zone_header () + '\n'.join (mgmt_records) + '\n'
	)
	write_zone_file (
		os.path.join (bind_dir, 'db.10.10.10'),
		zone_header () + '\n'.join (reverse_mgmt_records) + '\n'
	)
	write_zone_file (
		os.path.join (bind_dir, 'db.home.net'),
		zone_header () + '\n'.join (home_records) + '\n'
	)
	write_zone_file (
		os.path.join (bind_dir, 'db.nbn.net'),
		zone_header () + '\n'.join (nbn_records) + '\n'
	)

	write_zone_file (
		os.path.join (bind_dir, 'db.cdn.net'),
		zone_header () + '\n'.join (cdn_records) + '\n'
	)
	write_zone_file (
		os.path.join (bind_dir, 'db.172.20.1'),
		zone_header () + '\n'.join (reverse_cdn_records) + '\n'
	)
	write_zone_file (
		os.path.join (bind_dir, 'db.rsp.net'),
		zone_header () + '$ORIGIN rsp.net.\n\nrsp-int-cust\tA\t172.16.1.1\nrsp-ext\t\tA\t172.16.1.254\n'
	)
	write_zone_file (
		os.path.join (bind_dir, 'db.172.16.1'),
		zone_header () + '$ORIGIN 1.16.172.in-addr.arpa.\n\n1\tPTR\trsp-int-cust.rsp.net.\n254\tPTR\trsp-ext.rsp.net.\n'
	)
	# Keep a compatibility copy for tooling that still expects the historical filename.
	first_subnet = FIRST_CLIENT_SUBNET
	write_zone_file (
		os.path.join (bind_dir, 'db.192.168.100'),
		zone_header () + f'$ORIGIN {first_subnet}.168.192.in-addr.arpa.\n\n1\tPTR\tclient1.home.net.\n2\tPTR\tclient2.home.net.\n254\tPTR\thouse1-gw.home.net.\n'
	)

def log (s, col = "green"):
	cprint (s, col)

class Router (Switch):
	"""Defines a new router that is inside a network namespace so that the
	individual routing entries don't collide.

	"""
	ID = 0
	def __init__(self, name, **kwargs):
		kwargs['inNamespace'] = True
		Switch.__init__(self, name, **kwargs)
		Router.ID += 1
		self.switch_id = Router.ID

	@staticmethod
	def setup ():
		return

	def start (self, controllers):
		pass

	def stop (self):
		self.deleteIntfs()

	def log (self, s, col="magenta"):
		cprint (s, col)

class GenericSwitch (Switch):
	"""Defines a new gateway that is NOT inside a network namespace.
	"""
	ID = 0
	def __init__(self, name, **kwargs):
		kwargs['inNamespace'] = False
		Switch.__init__(self, name, **kwargs)
		GenericSwitch.ID += 1
		self.switch_id = GenericSwitch.ID

	@staticmethod
	def setup ():
		return

	def start (self, controllers):
		pass

	def stop (self):
		self.deleteIntfs()

	def log (self, s, col="magenta"):
		cprint (s, col)

class NBNTopo (Topo):
	def __init__ (self):
# Add default members to class.
		super (NBNTopo, self).__init__ ()
# Control
#		s1 = self.addSwitch ('s1', cls=LinuxBridge, dpid='0000000000000001', inNamespace=True)
# Servers

# Customer LAN switch (customer L2/L3 network), 192.168.100.0/24

		routers = []
		switches = []
		clients = []
		servers = []

		household_switches = []
		household_routers = []
		mgmt_switch = self.addSwitch ('sm', dpid='0000000000000008', inNamespace=True, cls=LinuxBridge)
		switches.append (mgmt_switch)

# Switch representing NBN L2 service between customer and RSP - there might be a bunch of others following this one, but for now just the one.
		s2 = self.addSwitch ('s2', dpid='0000000000000003', inNamespace=True, cls=LinuxBridge)
		switches.append (s2)

# Router representing RSP-to-customer interface, 10.1.1.2/30 external, 172.16.1.1/24 internal
		r2 = self.addSwitch ('r2', dpid='0000000000000004', inNamespace=True)
		routers.append (r2)

# RSP internal network
		s3 = self.addSwitch ('s3', dpid='0000000000000005', inNamespace=True, cls=LinuxBridge)
		switches.append (s3)

# RSP to internet connection, 172.16.1.254/24 internal, 172.20.1.1/24 external
		r3 = self.addSwitch ('r3', dpid='0000000000000006', inNamespace=True)
		routers.append (r3)

# Content servers in 172.20.1.0/24 connected to RSP via s3
		s4 = self.addSwitch ('s4', dpid='0000000000000007', inNamespace=True, cls=LinuxBridge)
		switches.append (s4)

		client_index = 1
		for household in range (1, args.households + 1):
			lan_switch = self.addSwitch ('s1h%i' % household, dpid='00000000000001%02i' % household, inNamespace=True, cls=LinuxBridge)
			lan_router = self.addSwitch ('hr%i' % household, dpid='00000000000002%02i' % household, inNamespace=True)
			household_switches.append (lan_switch)
			household_routers.append (lan_router)
			switches.append (lan_switch)
			routers.append (lan_router)

			subnet_octet = FIRST_CLIENT_SUBNET + household - 1
			switch_mgmt_octet = MGMT_PLAN['household_switches'][household]
			router_mgmt_octet = MGMT_PLAN['household_routers'][household]
			self.addLink (lan_switch, lan_router, intfName1='s1h%i-hr%i' % (household, household), intfName2='hr%i-s1h%i' % (household, household), params2={'ip':'192.168.%i.254/24' % subnet_octet})
			self.addLink (lan_router, s2, intfName1='hr%i-s2' % household, intfName2='s2-hr%i' % household, params1={'ip':'10.1.%i.1/30' % household})
			self.addLink (lan_router, mgmt_switch, intfName1='mgmt0', params1={'ip':'10.10.10.%i/24' % router_mgmt_octet}, intfName2='sm-hr%i' % household)
			self.addLink (lan_switch, mgmt_switch, intfName1='mgmt0', params1={'ip':'10.10.10.%i/24' % switch_mgmt_octet}, intfName2='sm-s1h%i' % household)

			for household_client in range (1, args.clients_per_household + 1):
				client_mgmt_octet = MGMT_PLAN['clients'][client_index]
				host = self.addHost ('client%i' % client_index, ip='192.168.%i.%i/24' % (subnet_octet, household_client), defaultRoute='via 192.168.%i.254' % subnet_octet)
				clients.append (host)
				self.addLink (host, lan_switch, intfName1=('client%i-s1h%i' % (client_index, household)), intfName2=('s1h%i-client%i' % (household, client_index)), params1={'ip':('192.168.%i.%i/24' % (subnet_octet, household_client))})
				self.addLink (host, mgmt_switch, intfName1='mgmt0', intfName2=('sm-client%i' % client_index), params1={'ip':('10.10.10.%i/24' % client_mgmt_octet)})
				client_index += 1

		for n in range (1, args.servers + 1):
			server_mgmt_octet = MGMT_PLAN['servers'][n]
			host = self.addHost ('server%i' % n, ip='172.20.1.%i/24' % n, defaultRoute='via 172.20.1.254')
			servers.append (host)
			self.addLink (servers[n - 1], s4, intfName1=('server%i-s4' % n), intfName2=('s4-server%i' % n), params1={'ip':('172.20.1.%i/24' % n)})
			self.addLink (servers[n - 1], mgmt_switch, intfName1='mgmt0', intfName2=('sm-server%i' % n), params1={'ip':('10.10.10.%i/24' % server_mgmt_octet)})

# Inter switch/router links
		self.addLink (s2, r2, intfName1='s2-r2', intfName2='r2-s2', params2={'ip':'10.1.1.2/30'})
		self.addLink (r2, s3, intfName1='r2-s3', intfName2='s3-r2', params1={'ip':'172.16.1.1/24'})
		self.addLink (s3, r3, intfName1='s3-r3', intfName2='r3-s3', params2={'ip':'172.16.1.254/24'})
		self.addLink (r3, s4, intfName1='r3-s4', intfName2='s4-r3', params1={'ip':'172.20.1.254/24'})

# Management links to everything
		dns = self.addHost ('dns', ip='10.10.10.254/24')

# Routers to mgmt
		self.addLink (r2, mgmt_switch, intfName1='mgmt0', params1={'ip':'10.10.10.2/24'}, intfName2='sm-r2')
		self.addLink (r3, mgmt_switch, intfName1='mgmt0', params1={'ip':'10.10.10.3/24'}, intfName2='sm-r3')

# Switches to mgmt
		self.addLink (s2, mgmt_switch, intfName1='mgmt0', params1={'ip':'10.10.10.12/24'}, intfName2='sm-s2')
		self.addLink (s3, mgmt_switch, intfName1='mgmt0', params1={'ip':'10.10.10.13/24'}, intfName2='sm-s3')
		self.addLink (s4, mgmt_switch, intfName1='mgmt0', params1={'ip':'10.10.10.14/24'}, intfName2='sm-s4')

		self.addLink (dns, mgmt_switch, intfName1='dns-sm', intfName2='sm-dns')

def startBindMount (node):
	node.cmd ("/bin/rm -rf /tmp/run-%s && /bin/mkdir -p /tmp/run-%s && /bin/mount --bind /tmp/run-%s /run" % (node.name, node.name, node.name))
	node.waitOutput ()

	return

def disabletso (node):
# Apply ethtool to turn off TCP Segmentation Offload
	node.cmd ("for iface in `/bin/ip link | /bin/grep -- -eth | /usr/bin/cut -f 2 -d ' ' | /usr/bin/cut -f 1  -d '@'` ; do /sbin/ethtool -K $iface tso off ; done")
	return

def setupDNS (node):
	node.cmd ("/bin/mkdir -p /run/resolvconf && /bin/mkdir -p /tmp/resolvconf-%s && /bin/mount --bind /tmp/resolvconf-%s /etc/resolvconf" % (node.name, node.name))
	node.waitOutput ()
	node.cmd ("/bin/ln -sf /run/resolvconf /etc/resolvconf && echo 'nameserver 10.10.10.254' > /run/resolvconf/resolv.conf && echo 'search home.net nbn.net rsp.net cdn.net mgmt.net' >> /run/resolvconf/resolv.conf")
	node.waitOutput ()

	return

def terminate_process (proc_list):
	for proc in proc_list:
		if proc and proc.poll() is None:  # Check if the process is running
			print ("Terminating process %i" % proc.pid)
			os.kill (proc.pid, signal.SIGTERM)  # Terminate the process

def startserver (node, server_cmd):
	log ("Starting service '%s' on %s" % (server_cmd, node.name))
	server_proc = subprocess.Popen (['mnexec', '-a', str (node.pid), '--'] + server_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	return server_proc

def set_interface_bw (node, interface, bandwidth):
# Use a burst sized for high-rate links; a single-MTU burst heavily throttles TBF in practice.
	rate_mbit = int (round (bandwidth))
	burst_bytes = max (65536, int ((bandwidth * 1000 * 1000 / 8) * 0.05))

	print ('Bandwidth = %s Mb/s' % rate_mbit)
	log ("Setting egress bandwidth on %s:%s to %iMb/s (burst %i bytes)" % (node.name, interface, rate_mbit, burst_bytes))
	node.cmd ("/sbin/tc qdisc replace dev %s root handle 1: tbf rate %smbit burst %ib latency 50ms" % (interface, rate_mbit, burst_bytes))

def set_interface_latency_loss (node, interface, latency, jitter, correlation, loss):
	log ("Setting latency on %s:%s to %i ms with %i ms jitter and %i%% correlation (Pareto distribution)" % (node.name, interface, latency, jitter, correlation))
	node.cmd ("/sbin/tc qdisc add dev %s root netem delay %ims %ims %i%% distribution pareto" % (interface, latency, jitter, correlation))

def main ():
	os.system ("/bin/rm -f /tmp/r*.log /tmp/r*.pid logs/*")
	os.system ("/bin/killall -9 named > /dev/null 2>&1")

	required_clients = args.households * args.clients_per_household
	if args.clients != required_clients:
		parser.error ("This household scenario requires exactly %i clients" % required_clients)
	if FIRST_CLIENT_SUBNET + args.households - 1 > 254:
		parser.error ("Household count is too large for the current client subnet allocation plan")

	generate_bind_files (BIND_DIR, args.households, args.clients_per_household, args.servers, MGMT_PLAN)

	topo = NBNTopo()

	test_name = "visualisation"
	mutils = mininet_utils.mininet_utils(config.config['output_dir'], test_name)
	base_dir = config.config['output_dir'] + test_name + '/'
	mutils.create_directories ()
	mutils.create_topology_diagram (topo)

	net = Mininet (topo = topo, switch = Router)

	net.start ()

#	startBridge(net.switches[0])

	for node in net.switches:
		startBindMount (node)
		node.cmd ("/sbin/sysctl -w net.ipv4.ip_forward=1")
		node.cmd ("/sbin/ifup lo") # why this doesn't happen by default is beyond my comprehension
		node.waitOutput ()
		setupDNS (node)
		node.cmd ("mkdir -p /run/sshd")
		server_processes.append (startserver (node, ["/sbin/sshd", "-D"]))
		disabletso (node)

	s2 = net.get ('s2')
	r2 = net.get ('r2')
	r3 = net.get ('r3')

	for household in range (1, args.households + 1):
		subnet_octet = FIRST_CLIENT_SUBNET + household - 1
		household_router = net.get ('hr%i' % household)

		if household > 1:
			r2.cmd ('/sbin/ip addr add 10.1.%i.2/30 dev r2-s2' % household)

		household_router.cmd ('/sbin/ip route add default via 10.1.%i.2' % household)
		household_router.cmd ('/sbin/ip route add 172.16.1.0/24 via 10.1.%i.2' % household)
		household_router.cmd ('/sbin/ip route add 172.20.1.0/24 via 10.1.%i.2' % household)
		r2.cmd ('/sbin/ip route add 192.168.%i.0/24 via 10.1.%i.1 dev r2-s2' % (subnet_octet, household))

# This is r2 - the rsp-residential gateway
	r2.cmd ('/sbin/ip route add 172.20.1.0/24 via 172.16.1.254');

# This is r3 - the rsp-csp gateway
	r3.cmd ('/sbin/ip route add 10.1.0.0/16 via 172.16.1.1');
	for household in range (1, args.households + 1):
		subnet_octet = FIRST_CLIENT_SUBNET + household - 1
		r3.cmd ('/sbin/ip route add 192.168.%i.0/24 via 172.16.1.1' % subnet_octet);

# For now:
	latency = 2
	jitter = 2
	correlation = 50
	loss = 0

# Apply household service rates and shared aggregation bottleneck
	for household in range (1, args.households + 1):
		household_router = net.get ('hr%i' % household)
		set_interface_bw (s2, 's2-hr%i' % household, HOUSEHOLD_DOWNSTREAM)
		set_interface_bw (household_router, 'hr%i-s2' % household, HOUSEHOLD_UPSTREAM)

	set_interface_bw (r2, 'r2-s2', args.downstream)
	set_interface_bw (s2, 's2-r2', args.upstream)

# This looks confusing; it is saying do a bind mount of the folder ../bind to /etc/bind (bind = berkely internet name daemon aka DNS server)
#	log ("Performing bind mount for bind configuration folder, and starting BIND daemon")

#	startBindMount (net.switches[-1])
#	net.switches[-1].cmd ('/sbin/brctl delif s1 s1-sm')
#	net.switches[-1].cmd ('/sbin/ifup lo')
#	setupDNS (net.switches[-1])

	for host in net.hosts:
		startBindMount (host)
		disabletso (host)
		host.cmd ("mkdir -p /run/sshd")
		server_processes.append (startserver (host, ["/sbin/sshd", "-D"]))
		server_processes.append (startserver (host, ["/sbin/nginx", "-g", "daemon off;"]))
		server_processes.append (startserver (host, ["/usr/bin/ITGRecv"]))
		setupDNS (host)

		if host.name.startswith ('server'):
			for port in range (IPERF_BASE_PORT, IPERF_BASE_PORT + IPERF_PORTS_PER_SERVER):
				server_processes.append (startserver (host, ["/usr/bin/iperf3", "-s", "-p", str (port), "-f", "K"]))
		else:
			server_processes.append (startserver (host, ["/usr/bin/iperf3", "-s", "-f", "K"]))

		if host.name == 'dns':
			host.cmd ('/bin/mount --bind bind /etc/bind && /bin/mkdir -p /run/named && /bin/chown bind.bind /run/named && named -u bind -4 -L /tmp/bind.log')

	atexit.register (terminate_process, server_processes)
	
#	CLI (net)
	net.hosts[-1].cmd ("cd perfmon ; /usr/bin/python3 ./run_experiments.py &> /tmp/experiment.log")

	net.stop ()
	os.system ("/usr/bin/killall -9 named > /dev/null 2>&1")

if __name__ == "__main__":
	setLogLevel ('info')
	main ()
